#!/usr/bin/env python3
"""Build docs/journal/journal.md and index.html from manifest + reports/*.md."""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
JOURNAL = ROOT / "docs" / "journal"
MANIFEST_PATH = JOURNAL / "journal.manifest.json"
REPORTS_DIR = JOURNAL / "reports"
JOURNAL_MD_PATH = JOURNAL / "journal.md"
INDEX_MD_PATH = JOURNAL / "index.md"
INDEX_HTML_PATH = JOURNAL / "index.html"

MD_EXTENSIONS = ["tables", "fenced_code", "nl2br", "sane_lists"]


def load_manifest() -> dict:
    with MANIFEST_PATH.open(encoding="utf-8") as f:
        return json.load(f)


def load_report_body(filename: str) -> str:
    return (REPORTS_DIR / filename).read_text(encoding="utf-8")


def rewrite_image_paths_for_html(text: str) -> str:
    return text.replace("](../screenshots/", "](screenshots/")


def rewrite_image_paths_for_journal_md(text: str) -> str:
    return text.replace("](../screenshots/", "](screenshots/")


def strip_report_preamble(report_md: str) -> str:
    """Drop duplicate title/metadata block; section header comes from manifest in HTML."""
    lines = report_md.splitlines()
    if not lines or not lines[0].startswith("# "):
        return report_md

    out: list[str] = []
    skipped_front = True
    for line in lines[1:]:
        if skipped_front:
            if line.strip() == "---":
                skipped_front = False
            continue
        out.append(line)
    return "\n".join(out).lstrip("\n")


def md_to_html_fragment(text: str) -> str:
    converted = markdown.markdown(
        rewrite_image_paths_for_html(text),
        extensions=MD_EXTENSIONS,
    )
    return converted


def build_scenes_table_md(scenes: list[dict]) -> str:
    lines = [
        "## Unity scenes",
        "",
        "| Scene | Experiment | Runners | Notes |",
        "|-------|------------|---------|-------|",
    ]
    for scene in scenes:
        notes = scene.get("formerly", "")
        if notes:
            notes = f"Renamed from `{notes}`"
        lines.append(
            f"| `{scene['path']}` | {scene['experiment']} | {scene['runners']} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_index_table_md(reports: list[dict]) -> str:
    lines = [
        "## Report index",
        "",
        "| Date | Experiment | Status | Unity scene | Report |",
        "|------|------------|--------|-------------|--------|",
    ]
    for report in reports:
        exp = f"{report['experiment_id']} — {report['title']}"
        report_file = report["file"]
        section_id = report["section_id"]
        lines.append(
            f"| {report['date']} | {exp} | {report['status']} | `{report['unity_scene']}` | "
            f"[Markdown](reports/{report_file}) · [HTML](index.html#{section_id}) |"
        )
    lines.append("")
    return "\n".join(lines)


def build_journal_md(manifest: dict, reports: list[dict]) -> str:
    parts = [
        f"# {manifest['title']}",
        "",
        manifest.get("subtitle", "Assembled from `reports/*.md`. Edit reports, then run `python Tools/build_journal.py`."),
        "",
        "_Generated by `Tools/build_journal.py`. Do not hand-edit; edit `reports/*.md` or `journal.manifest.json` instead._",
        "",
        build_scenes_table_md(manifest.get("scenes", [])),
        build_index_table_md(reports),
        "---",
        "",
    ]

    for report in reports:
        body = rewrite_image_paths_for_journal_md(load_report_body(report["file"]))
        parts.extend(
            [
                f"<!-- report: {report['section_id']} -->",
                f"<a id=\"{report['section_id']}\"></a>",
                "",
                body.rstrip(),
                "",
                "---",
                "",
            ]
        )

    return "\n".join(parts).rstrip() + "\n"


def build_index_md(manifest: dict, reports: list[dict]) -> str:
    parts = [
        "# Experiment Journal Index",
        "",
        build_scenes_table_md(manifest.get("scenes", [])),
        build_index_table_md(reports),
        "**Browse all reports:** [journal.md](journal.md) (full markdown) · [index.html](index.html) (mobile-friendly)",
        "",
    ]
    return "\n".join(parts)


def build_nav_html(reports: list[dict]) -> str:
    items = []
    for report in reports:
        label = f"{report['date']} · {report['experiment_id']} {report['title']}"
        items.append(
            f'          <li><a href="#{html.escape(report["section_id"])}">{html.escape(label)}</a></li>'
        )
    return "\n".join(items)


def build_section_html(report: dict) -> str:
    body_md = strip_report_preamble(load_report_body(report["file"]))
    body_html = md_to_html_fragment(body_md)
    verdict = report.get("verdict") or {}
    verdict_class = html.escape(verdict.get("class", ""))
    verdict_label = html.escape(verdict.get("label", ""))
    verdict_html = ""
    if verdict_class and verdict_label:
        verdict_html = f'\n        <div class="verdict-{verdict_class}">{verdict_label}</div>\n'

    return f"""      <section id="{html.escape(report["section_id"])}">
        <h2>{html.escape(report["experiment_id"])} — {html.escape(report["title"])}</h2>
        <div class="meta">
          <strong>Date:</strong> {html.escape(report["date"])} &nbsp;|&nbsp;
          <strong>ID:</strong> {html.escape(report["experiment_id"])} &nbsp;|&nbsp;
          <strong>Status:</strong> {html.escape(report["status"])} &nbsp;|&nbsp;
          <strong>Scene:</strong> <code>{html.escape(report["unity_scene"])}</code>
        </div>
{verdict_html}        <div class="report-body">
{body_html}
        </div>
        <p class="report-link">
          <a href="reports/{html.escape(report["file"])}">Source markdown</a>
        </p>
      </section>"""


def build_scenes_section_html(scenes: list[dict]) -> str:
    rows = []
    for scene in scenes:
        note = ""
        if scene.get("formerly"):
            note = f"Renamed from <code>{html.escape(scene['formerly'])}</code>"
        rows.append(
            "<tr>"
            f"<td><code>{html.escape(scene['path'])}</code></td>"
            f"<td>{html.escape(scene['experiment'])}</td>"
            f"<td>{html.escape(scene['runners'])}</td>"
            f"<td>{note}</td>"
            "</tr>"
        )
    rows_html = "\n          ".join(rows)
    return f"""      <section id="unity-scenes">
        <h2>Unity scenes</h2>
        <p>Preset scenes under <code>Assets/Scenes/</code> (formerly a single <code>SampleScene.unity</code>).</p>
        <table>
          <tr><th>Scene</th><th>Experiment</th><th>Runners</th><th>Notes</th></tr>
          {rows_html}
        </table>
      </section>"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0f1419;
      --surface: #1a2332;
      --border: #2d3a4d;
      --text: #e8eef4;
      --muted: #9aa8b8;
      --accent: #f0c040;
      --pass: #5ecf8a;
      --fail: #e07a7a;
      --link: #7eb8ff;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      font-size: 16px;
      line-height: 1.55;
      background: var(--bg);
      color: var(--text);
    }}
    a {{ color: var(--link); }}
    header {{
      position: sticky;
      top: 0;
      z-index: 10;
      background: var(--surface);
      border-bottom: 1px solid var(--border);
      padding: 0.75rem 1rem;
    }}
    header h1 {{
      margin: 0;
      font-size: 1.1rem;
      color: var(--accent);
    }}
    header p {{
      margin: 0.25rem 0 0;
      font-size: 0.85rem;
      color: var(--muted);
    }}
    .layout {{
      display: flex;
      flex-direction: column;
      max-width: 900px;
      margin: 0 auto;
    }}
    nav {{
      background: var(--surface);
      border-bottom: 1px solid var(--border);
      padding: 0.5rem 1rem;
    }}
    nav summary {{
      cursor: pointer;
      font-weight: 600;
      color: var(--accent);
      list-style: none;
    }}
    nav summary::-webkit-details-marker {{ display: none; }}
    nav ul {{
      margin: 0.5rem 0 0;
      padding-left: 1.2rem;
    }}
    nav li {{ margin: 0.35rem 0; }}
    main {{ padding: 1rem; }}
    section {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1rem 1.1rem;
      margin-bottom: 1.25rem;
    }}
    section h2 {{
      margin: 0 0 0.35rem;
      font-size: 1.15rem;
      color: var(--accent);
    }}
    .meta {{
      font-size: 0.88rem;
      color: var(--muted);
      margin-bottom: 1rem;
    }}
    .meta strong {{ color: var(--text); }}
    .report-body h2, .report-body h3, .report-body h4 {{
      color: var(--text);
      margin: 1.25rem 0 0.5rem;
    }}
    .report-body h2 {{ font-size: 1rem; }}
    .report-body h3 {{ font-size: 0.95rem; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 0.92rem;
      margin: 0.5rem 0 1rem;
    }}
    th, td {{
      border: 1px solid var(--border);
      padding: 0.45rem 0.55rem;
      text-align: left;
    }}
    th {{ background: #243044; color: var(--accent); }}
    .verdict-fail {{
      display: inline-block;
      background: #3d2020;
      color: var(--fail);
      border: 1px solid var(--fail);
      border-radius: 4px;
      padding: 0.35rem 0.6rem;
      font-weight: 700;
      margin: 0.5rem 0;
    }}
    .verdict-obs {{
      display: inline-block;
      background: #1e2a3d;
      color: var(--link);
      border: 1px solid var(--link);
      border-radius: 4px;
      padding: 0.35rem 0.6rem;
      font-weight: 700;
      margin: 0.5rem 0;
    }}
    .report-link {{
      font-size: 0.88rem;
      color: var(--muted);
      margin-top: 1rem;
    }}
    .report-body img {{
      display: block;
      max-width: 100%;
      height: auto;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: #0a0e14;
      margin: 0.75rem 0;
    }}
    .report-body em {{
      color: var(--muted);
      font-size: 0.9rem;
    }}
    .report-body ul, .report-body ol {{ padding-left: 1.2rem; }}
    .report-body li {{ margin: 0.35rem 0; }}
    .report-body p {{ margin: 0.6rem 0; }}
    .report-body code {{
      background: #243044;
      padding: 0.1rem 0.35rem;
      border-radius: 3px;
      font-size: 0.9em;
    }}
    footer {{
      text-align: center;
      padding: 1.5rem 1rem 2rem;
      font-size: 0.8rem;
      color: var(--muted);
    }}
    @media (min-width: 720px) {{
      .layout {{ flex-direction: row; align-items: flex-start; }}
      nav {{
        width: 240px;
        flex-shrink: 0;
        position: sticky;
        top: 4.5rem;
        border-bottom: none;
        border-right: 1px solid var(--border);
        min-height: calc(100vh - 4.5rem);
      }}
      nav details {{ display: block; }}
      nav summary {{ display: none; }}
      nav ul {{ display: block !important; }}
      main {{ flex: 1; padding: 1.25rem; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p>{subtitle} · built from markdown</p>
  </header>

  <div class="layout">
    <nav>
      <details open>
        <summary>Reports</summary>
        <ul>
          <li><a href="#unity-scenes">Unity scenes</a></li>
{nav}
        </ul>
      </details>
    </nav>

    <main>
{scenes_section}
{sections}
    </main>
  </div>

  <footer>
    MazeLifeLab · docs/journal · source: journal.md + reports/ · rebuild: python Tools/build_journal.py
  </footer>
</body>
</html>
"""


def build_index_html(manifest: dict, reports: list[dict]) -> str:
    sections = "\n\n".join(build_section_html(r) for r in reports)
    scenes_section = build_scenes_section_html(manifest.get("scenes", []))
    return HTML_TEMPLATE.format(
        title=html.escape(manifest["title"]),
        subtitle=html.escape(manifest.get("subtitle", "")),
        nav=build_nav_html(reports),
        scenes_section=scenes_section,
        sections=sections,
    )


def sorted_reports(manifest: dict) -> list[dict]:
    return sorted(manifest["reports"], key=lambda r: r.get("sort_order", 999))


def main() -> None:
    manifest = load_manifest()
    reports = sorted_reports(manifest)

    JOURNAL_MD_PATH.write_text(build_journal_md(manifest, reports), encoding="utf-8")
    INDEX_MD_PATH.write_text(build_index_md(manifest, reports), encoding="utf-8")
    INDEX_HTML_PATH.write_text(build_index_html(manifest, reports), encoding="utf-8")

    print(f"Wrote {JOURNAL_MD_PATH.relative_to(ROOT)}")
    print(f"Wrote {INDEX_MD_PATH.relative_to(ROOT)}")
    print(f"Wrote {INDEX_HTML_PATH.relative_to(ROOT)}")
    print(f"Reports: {len(reports)}")


if __name__ == "__main__":
    main()
